// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 1/17/2026, 4:10:36 PM
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.ts";
const config = [
{"content":{"files":["/Users/maxi/www/curriculum/web/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/maxi/www/curriculum/web/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/maxi/www/curriculum/web/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/maxi/www/curriculum/web/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/maxi/www/curriculum/web/plugins/**/*.{js,ts,mjs}","/Users/maxi/www/curriculum/web/composables/**/*.{js,ts,mjs}","/Users/maxi/www/curriculum/web/utils/**/*.{js,ts,mjs}","/Users/maxi/www/curriculum/web/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/maxi/www/curriculum/web/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","/Users/maxi/www/curriculum/web/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","/Users/maxi/www/curriculum/web/app.config.{js,ts,mjs}"]}},
{},
cfg2
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;